### ISSUE TITLE
feedback and or bug

### ISSUE THREAD

**Issue by hn-88** [NapoleonWils0n/ffmpeg-scripts#1]
Hi,

When I run overlay-pip with 
./overlay-pip -i "East Perth Harbour ghosts.mp4" -v Earth720.mp4  -p 2 
I get something like the attached file. That is, the overlay is happening twice, with 

1. the correct overlay video, Earth720, appearing on the left instead of as a pip

2. the 'background' video appearing as pip on the right hand side overlaid on itself.

![Screenshot from East Perth Harbour ghosts-pip-2020-05-09-08-54-17 mp4](https://user-images.githubusercontent.com/6321069/81462915-64978500-91d3-11ea-9b43-aedeef4e87f6.jpg)

**Comment by hn-88** [comment]
Interestingly, for
./overlay-pip -i Earth720.mp4 -v "East Perth Harbour ghosts.mp4"   -p 2
I get Earth as the pip instead of harbour. Initially Earth is seen (for the first 2 seconds, as I gave -p 2) Then Earth becomes small, and harbour becomes the background, but with the aspect ratio of Earth.

![Screenshot from Earth720-pip-2020-05-09-09-11-41 mp4](https://user-images.githubusercontent.com/6321069/81463252-bf31e080-91d5-11ea-87e7-36d057a5ecd2.jpg)

**Comment by NapoleonWils0n** [comment]
hi mate

the videos have to be exactly the same or you might gets some odd issues

eg the videos have to be the same size, aspect ratio, framerate etc

have you tried using the same video for both base video and the overlay,
to see if you get any issues

looking at the images the videos look like they have a different aspect ratio

**Comment by hn-88** [comment]
If you use the same video for both the base and overlay, you may not be able to distinguish the issues :) If I use this, for example, two videos with exactly the same number of pixels and aspect ratio,
``` ./overlay-pip -i Video3.mp4 -v "East Perth Harbour ghosts.mp4"   -p 2 ```
At first Video3 plays,
![Screenshot from 2020-05-10 08-47-28](https://user-images.githubusercontent.com/6321069/81490090-544add00-929b-11ea-9c34-9a86dbc838aa.jpg)
then at the 2 second mark, Video3 becomes the pip,
![Screenshot from 2020-05-10 08-47-54](https://user-images.githubusercontent.com/6321069/81490097-66c51680-929b-11ea-9055-de3711b9ab0a.jpg)

**Comment by NapoleonWils0n** [comment]
hi mate
my bad i didnt mean the same video silly typo
i meant videos encoded the same way eg size, frame rate codec

the script will put the base video in the pip window

and replace the base video with the overlay video
when the the overlay video stops playing the main video in the pip window goes back to the main window

where you expecting it to work the other way around or something

**Comment by hn-88** [comment]
> 
> the script will put the base video in the pip window
> 
> and replace the base video with the overlay video
> when the the overlay video stops playing the main video in the pip window goes back to the main window
> 
> where you expecting it to work the other way around or something

Ah! Yes. So, if this is the expected behaviour, then everything is fine :)
