### ISSUE TITLE
tile-thumbnails fails on Windows due to the usage of bc in line 138

### ISSUE THREAD

**Issue by warduweram** [NapoleonWils0n/ffmpeg-scripts#3]
Hey!

Thanks for your work on these excellent scripts. Unfortunately, I can't bring the tile-thumbnails script to work on Windows, it exits with "line 138: bc: command not found". From what I could gather this could be related to bc requiring commands to be terminated with "\n" and ffprobe on Windows containing CR and LF.
It might be another issue, though, I don't know.

https://superuser.com/questions/1647642/using-variables-with-bc-syntax-error

Thanks in advance for looking into this!

**Comment by NapoleonWils0n** [comment]
Hi Mate, you need to install the bc command which is used as a calculator

your right about the line endings, 
im not a windows user but  that rings a bell

if possible its best to use wsl to install the scipts 
[windows run shell scripts with wsl](https://www.youtube.com/watch?v=N8t9W3u6cxc)

then you wont get any line ending issues

or you can install bc with cywgin
[cygwin bc](https://www.cygwin.com/packages/summary/bc.html)

[scene detect on windows with cygwin](https://www.youtube.com/watch?v=hu8ZnzIsEmQ)

let me know if that helps

**Comment by warduweram** [comment]
Hey!

Thanks so much, that did the trick. And sorry, I didn't consider that I might just be missing a package, I'm mostly a GUI Windows user and I keep forgetting stuff when I get back to the command line. ;-) Can't install either WSL nor Docker on my machine, either btw, but I already did have MSYS installed and could get bc through that.
