### ISSUE TITLE
Cutting commercials

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/ffmpeg-scripts#4]
Good morning Sir,  I was wondering what steps should i do with your ffmpeg scripts to cut commercials on my tv shows i recorded  awhile back?  I'm playing on Ubuntu.

                                                                                                                                        Thank you
                                                                                                                                              Steve

**Comment by NapoleonWils0n** [comment]
Hi Steve, there is actually an ffmpeg filter called black detect which is what most people use to detect ads

that would probably be the best tool for the job

[ffmpeg black detect filter](https://ffmpeg.org/ffmpeg-filters.html#blackdetect)

[using-ffmpegs-blackdetect-filter-to-identify-commercial-blocks](https://blog.gdeltproject.org/using-ffmpegs-blackdetect-filter-to-identify-commercial-blocks/)

there is also something called comskip which i think can be used with kodi

[comskip](https://github.com/erikkaashoek/Comskip)

edit decision lists

[kodi edl](https://kodi.wiki/view/Edit_decision_list)

hop that helps
