### ISSUE TITLE
Issue with tile-thumbnails with timestamps 

### ISSUE THREAD

**Issue by electrohad** [NapoleonWils0n/ffmpeg-scripts#6]
First of all thank you for your collection of script 

I notice that when I 'm trying to use the option -x on with the thumbnail script 
It's trying to pass the following command 

`+ ffmpeg -hide_banner -stats -v panic -ss 00:00:05 -i /usr/data/covers/test.avi -frames 1 -vf $'drawtext=text=\'%{pts\\:hms\\:5}\':x=\'(main_w-text_w)/2\':y=\'(main_h-text_h)\':fontcolor=white:fontsize=\'(main_h/8)\':boxcolor=black:box=1,select=not(mod(n\\,26692)),scale=160:-1,tile=4x2:padding=7:margin=2:color=black' /usr/data/covers/test.png
`
and nothing is happening 

I'm using  ffmpeg version 6.1.1

**Comment by electrohad** [comment]
My bad I think it's missing one library for drawtext

**Comment by NapoleonWils0n** [comment]
hi mate,  no problem hope the scripts are useful

drawtext is used to display the timecode on the thumbnails

`tile-thumbnails -i duke-nuke-em.mp4 -w 320 -x on`

you need to use -x on

im running ffmpeg 6.1 on Freebsd 14.1
and just ran a test and didnt run into any issue

sounds like your right and your version of ffmpeg is missing drawtext for some reason

tile-thumbnails of me playing duke nukem
"come get some"

![duke-nuke-em-tile-2024-07-31-19-47-15](https://github.com/user-attachments/assets/df841fa5-2c56-4aea-8edb-54f1de0dba5a)

**Comment by electrohad** [comment]
I found out that I was missing the default font. So I added a parameter to define the font to use by drawtext and it's working smoothly . Thanks again 

I'm checking now if I can do something similar with "filter complex"  instead of "vf" to add a header on the png to display some information on the file.
I can keep you update if you are interested.
